blank_issues_enabled: false
template1: 
  - name: User Story
    url: https://github.com/wang-roy/devops-capstone-project/blob/main/.github/ISSUE_TEMPLATE/user-story.md
    about: This is a template for creating user stories
